export const ICON_NAMES = {
  MENU: 'menu-outline',
  SEARCH: 'search-outline',
  GOOGLE: 'logo-google',
  MOBILE: 'call',
  MAIL_OUTLINE: 'mail-outline',
  CHEVRON_DOWN: 'chevron-down',
  BACK_ARROW: 'arrow-back',
  EYE_OUTLINE: 'eye-outline',
  EYE_OFF_OUTLINE: 'eye-off-outline',
  LOCK_CLOSED_OUTLINE: 'lock-closed-outline',
  ADD: 'add',
  CLOSE: 'close',
  PERSON: 'person',
  PERSON_OUTLINE: 'person-outline',
  CHAT_BUBBLE: 'chatbubble',
  CHAT_BUBBLE_OUTLINE: 'chatbubble-outline',
  HEART: 'heart',
  HEART_OUTLINE: 'heart-outline',
} as const;
